### ISSUE TITLE
Simple example not working with count < 200

### ISSUE THREAD

**Issue by tomgratte** [baekgaard/peyetribe#1] opened 2014-04-02 09:31 UTC
You interface looks great. Many thanks for sharing.

Running your simple example fails for count < 200. It always fails at around count = 180, i.e. after 6 seconds. I cannot figure out why. Do you know why ?

Best regards and thanks for sharing
Thomas

**Comment by baekgaard** [comment] 2014-04-09 08:25
Hi Tom,

As mentioned also over on the eye tribe forum, this is usually caused by the heartbeat not running correctly. If you're using the file verbatim as a module (the way I suggested it), you actually need to comment out the last part of it, since the example code is left there.

Try to run it directly (i.e. "python peyetribe.py") and see if it will run also if you request, say, 1000 samples. That works here at least. If not, feel free to forward your code to me and I'll have a look.

**Comment by baekgaard** [comment] 2015-02-02 15:09
This should no(t) (longer be) a problem, so I'm closing this issue. 

I've seen a few instances where slow machines/strange scheduling between threads could cause a related issue, and have some time ago also reworked the code to fix that too, hopefully.

**Closed as completed by baekgaard** 2015-02-02 15:09 UTC
